### ISSUE TITLE
PHP Cache Seems Broken

### ISSUE THREAD

**Issue by mendelk** [arnaud-lb/MtHaml#83]
Cache works by confirming that `filemtime($cacheFile) !== filemtime($file)` before recompiling.

However, these might never work, because the time that it takes to create the compiled file may already make it false, thus causing it to recompile, thus making the difference even greater.

I can submit a PR for a fix changing the logic to something like this: `abs(filemtime($cacheFile) - filemtime($file)) > 5` (i.e: only recompile if there is a greater than 5 second difference), but I'm not at all convinced that this is best solution.

Thoughts?

**Comment by mendelk** [comment]
On second thought, perhaps a better solution would be manually [`touch`](https://secure.php.net/touch)ing the newly-compiled `$cacheFile` to match the `mtime` of `$file`.

**Comment by arnaud-lb** [comment]
You are right, well spotted ! touching the cache file after writing it seem to be a good solution. I will happily accept a PR for this :)
